// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWwGC9yiuDo-OttuMX3JFzSVsXFsQHwXs',
    appId: '1:102939880838:web:035844830706dd2701d007',
    messagingSenderId: '102939880838',
    projectId: 'olleysapp',
    authDomain: 'olleysapp.firebaseapp.com',
    storageBucket: 'olleysapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfNT59G19B-paQS0qGFrnLekPmHJmdff4',
    appId: '1:102939880838:android:f2fcaff4cbcb573e01d007',
    messagingSenderId: '102939880838',
    projectId: 'olleysapp',
    storageBucket: 'olleysapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByWschTDwUluXCJHWsVoj48fA3er9ozSU',
    appId: '1:102939880838:ios:d848814f0871dfa301d007',
    messagingSenderId: '102939880838',
    projectId: 'olleysapp',
    storageBucket: 'olleysapp.firebasestorage.app',
    iosBundleId: 'com.example.olleysApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByWschTDwUluXCJHWsVoj48fA3er9ozSU',
    appId: '1:102939880838:ios:d848814f0871dfa301d007',
    messagingSenderId: '102939880838',
    projectId: 'olleysapp',
    storageBucket: 'olleysapp.firebasestorage.app',
    iosBundleId: 'com.example.olleysApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWwGC9yiuDo-OttuMX3JFzSVsXFsQHwXs',
    appId: '1:102939880838:web:4d900e6ffaa1726f01d007',
    messagingSenderId: '102939880838',
    projectId: 'olleysapp',
    authDomain: 'olleysapp.firebaseapp.com',
    storageBucket: 'olleysapp.firebasestorage.app',
  );
}
